### job 配置项
jobs:
  java-sec:
    image: erda-registry.cn-hangzhou.cr.aliyuncs.com/erda/java-dependency-check-action:20201015-1f314fe
    resources:
      cpu: 1
      mem: 4096
    binds:
    # maven 依赖缓存
    - ((storageMountPoint))/devops/actions/java-dependency-check/maven-cache/.m2:/root/.m2
