jobs:
  mysqldump:
    image: erda-registry.cn-hangzhou.cr.aliyuncs.com/erda/mysqldump-action:20201028-0a4db20
    resources:
      cpu: 1
      mem: 2048
    binds:
    - ((storageMountPoint))/devops/actions/mysqldump/dump_result/:/tmp/dump_result/
