jobs:
  cs-kubernetes:
    image: erda-registry.cn-hangzhou.cr.aliyuncs.com/erda/cs-kubernetes:3.20
    resources:
      cpu: 0.2
      mem: 128
    binds:
    - ((storageMountPoint))/dice-ops/ecluster-configs:/opt/ecluster-configs:rw
